export const FILTER_PROJECT_CHANGED = 'FILTER_PROJECT_CHANGED';
export const FILTER_RANGE_CHANGED = 'FILTER_RANGE_CHANGED';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';
